### ISSUE TITLE
Unexpected token 'export' export { default } from './DataGrid';

### ISSUE THREAD

**Issue by mark-jeanswhse** [adazzle/react-data-grid#1936]
Have a project and running into issues building the project. Error occurs when importing react-data-grid

`import DataGrid from "react-data-grid";`

Below is build error:

export { default } from './DataGrid';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.gn5p (C:\Users\ITSupport\Documents\NodeJS\online-manifest\.next\server\static\ieHp7Bl9kRBjMJV-KHZw9\pages\index.js:384:18)
    at __webpack_require__ (C:\Users\ITSupport\Documents\NodeJS\online-manifest\.next\server\static\ieHp7Bl9kRBjMJV-KHZw9\pages\index.js:23:31)
    at Module.RNiq (C:\Users\ITSupport\Documents\NodeJS\online-manifest\.next\server\static\ieHp7Bl9kRBjMJV-KHZw9\pages\index.js:201:33)
    at __webpack_require__ (C:\Users\ITSupport\Documents\NodeJS\online-manifest\.next\server\static\ieHp7Bl9kRBjMJV-KHZw9\pages\index.js:23:31) {
  type: 'SyntaxError'
}

**Comment by qili26** [comment]
Maybe you need to include the react data grid lib during compiling phase as RDG is publishing ES6 modules.

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
![image](https://user-images.githubusercontent.com/25043398/73763054-8695ed00-4736-11ea-8967-f2f52653f8e7.png)

**Comment by binyominc** [comment]
@qili26 do you have any advice how to do that?  I am using electron react boilerplate, for what that's worth.

**Comment by qili26** [comment]
This is a similar issue (see the below link), as I don't know your code base and configuration, it's hard to say which piece went wrong actually.

So the gist is when you are bundling your code, you need to make sure the `node_modules/react-data-grid` is also getting compiled, because this `lib` is shipping ES modules now rather than the already compiled UMD js code.

https://github.com/webpack/webpack/issues/2017

**Comment by binyominc** [comment]
thanks

**Comment by armujahid** [comment]
I am getting this same error if I try SSR with `react-data-grid`. Client side rendering works fine with exact same code
![image](https://user-images.githubusercontent.com/3725386/76184929-897d7500-61ef-11ea-974c-3b180395df01.png)

I know that SSR is currently not supported and related PR has been marked stale https://github.com/adazzle/react-data-grid/pull/1459

Steps to reproduce:

1. Use `react-data-grid` with next.js in a page.
1. Ensure that client side rendering is working fine by loading some other page and navigation to  `react-data-grid` page (using Link tag)
1. Trigger server side rendering (by pressing F5 to refresh page)

**Comment by amanmahajan7** [comment]
SSR is currently not supported and we are happy to accept a PR

**Comment by barbalex** [comment]
> SSR is currently not supported and we are happy to accept a PR

Really? https://github.com/adazzle/react-data-grid/pull/1459
