### ISSUE TITLE
After cloning this project npm run build failed

### ISSUE THREAD

**Issue by lynshir** [adazzle/react-data-grid#2465]
clone this project,npm run install &  npm run build, but failed, Do you have any special configuration？
```
(plugin linaria) Error: /Users/feng_xy/0-project/react-data-grid/src/editors/TextEditor.tsx: classNameSlug option must return a string
src/editors/TextEditor.tsx
Error: /Users/feng_xy/0-project/react-data-grid/src/editors/TextEditor.tsx: classNameSlug option must return a string
    at GenerateClassNames (/Users/feng_xy/0-project/react-data-grid/node_modules/@linaria/rollup/node_modules/@linaria/babel-preset/src/visitors/GenerateClassNames.ts:122:13)
    at TaggedTemplateExpression (/Users/feng_xy/0-project/react-data-grid/node_modules/@linaria/rollup/node_modules/@linaria/babel-preset/src/extract.ts:133:15)
    at NodePath._call (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/context.js:110:16)
    at TraversalContext.visitSingle (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/context.js:79:19)
    at TraversalContext.visit (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/feng_xy/0-project/react-data-grid/node_modules/@babel/traverse/lib/path/context.js:97:18)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-data-grid@7.0.0-canary.49 build: `rollup --config --no-stdin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-data-grid@7.0.0-canary.49 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by nstepien** [comment]
Are you on the latest Node.js version?

**Comment by lynshir** [comment]
> Are you on the latest Node.js version?

`node v14.15.1`

Modify the rollup.config.js  in the plugins configuration
```
linaria()
```
It's working
