### ISSUE TITLE
TypeError: Cannot read property 'Symbol' of undefined in react-data-grid.ui-plugins.js:18258

### ISSUE THREAD

**Issue by aditi-vaidya** [adazzle/react-data-grid#449]
**I'm submitting a bug report**  (check one with "x")

```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
I am using the 'Rubix-Reactjs Powered Admin Template' for development(https://wrapbootstrap.com/theme/rubix-reactjs-powered-admin-template-WB09498FH). Here I am facing an issue when I try to import the 'react-data-grid/addons'.

I have imported the below modules in my js files as follows:
-import ReactDataGrid from 'react-data-grid';
-import ReactDataGridPlugins from 'react-data-grid/addons';

When I start the npm server I get the following error logs:
[dev:server] /home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:18258
[2]         var _Symbol = root.Symbol;
[2] ^
[2] TypeError: Cannot read property 'Symbol' of undefined
[2]     at symbolObservablePonyfill (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:18258:1)
[2]     at Object.defineProperty.value (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:18243:1)
[2]     at __webpack_require__ (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:30:1)
[2]     at Object.defineProperty.value (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:18216:1)
[2]     at **webpack_require** (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:30:1)
[2]     at Object.exports.**esModule (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:2413:1)
[2]     at __webpack_require** (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:30:1)
[2]     at Object.exports.**esModule (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:7536:1)
[2]     at __webpack_require** (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:30:1)
[2]     at Object.exports.__esModule (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:7978:1)

**Expected/desired behavior**
Should be able to use the 'ReactDataGridPlugins' for further use in project.

**Reproduction of the problem**
1. Use the 'Rubix-Reactjs Powered Admin Template'.
2. Install 'react-data-grid' using npm.
3. Import both the modules ReactDataGrid, ReactDataGridPlugins;
4. Start npm

**Comment by JohanNordlinder** [comment]
I'm also experiencing this issue when I try to import the addons using
`import {Toolbar} from 'react-data-grid/addons';` or `import ReactDataGridPlugins from 'react-data-grid/addons';`, my starter pack is https://github.com/erikras/react-redux-universal-hot-example.

Thanks in advance for assistance resolving this issue.

**Comment by jpdvi** [comment]
I was able to resolve this by changing `import {Toolbar} from 'react-data-grid/addons';` to i`mport {Toolbar} from 'react-data-grid/dist/react-data-grid.ui-plugins';`

**Comment by aditi-vaidya** [comment]
I tried using this:
`import {Toolbar} from 'react-data-grid/dist/react-data-grid.ui-plugins';`

But getting the same error:
```
[dev:server] /home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:18258
[2] 		var _Symbol = root.Symbol;
[2] ^
[2] [dev:server] TypeError: Cannot read property 'Symbol' of undefined
[2]     at symbolObservablePonyfill (/home/../alpha/tmp/webpack:/~/react-data-grid/dist/react-data-grid.ui-plugins.js:18258:1)
```

**Comment by philiiiiiipp** [comment]
I suppose you are trying to render server side? This library is not ready for that at the moment as far as I know.

A quick-fix would be to make sure the plugins are only loaded on the client side. E.g.

    let Toolbar = null;
    let Selectors = null;
    export default class ReactComponent extends Component {
    ...
      componentDidMount = () => {
        const ReactDataGridPlugins = require('react-data-grid/addons');
        Toolbar = ReactDataGridPlugins.Toolbar;
        Selectors = ReactDataGridPlugins.Data.Selectors;
      }
    ...
    }

And then define Toolbar and Selectors outside of the component.

**Comment by Wilfred** [comment]
Possibly a duplicate #361?

**Comment by philiiiiiipp** [comment]
I think its not (exactly) the same issue but comes down to the same problem: server side rendering.
Linking the two in some way might be a good idea so the person fixing #361 can also have this one in mind?

**Comment by diogofcunha** [comment]
As mentioned in some comments react-data-grid doesn't support server side rendering.

Is this server side rendering? If it is lets keep the conversation on #361.

Cheers.

**Comment by diogofcunha** [comment]
Closing due to inactivity
