### ISSUE TITLE
Isomorphic "support" (not exploding on isomorphic rendering)

### ISSUE THREAD

**Issue by noyg** [adazzle/react-data-grid#542]
**WHICH VERSION OF REACT ARE YOU USING?**
`15.1.0`
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**
`Node.js`
```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[ ] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When isomorphically rendering the component, the app cannot start. Stack trace:
```
C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:11023
	var scope = typeof (window) !== "undefined" ? (window) : self;
	                                                         ^

ReferenceError: self is not defined
    at Object.<anonymous> (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:11023:59)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.module.exports (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:10872:16)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.exports.__esModule (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:3644:14)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.exports.__esModule (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:14172:25)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.exports.__esModule (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:14076:25)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.exports.__esModule (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:14506:25)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.exports.__esModule (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:20225:17)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.<anonymous> (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:464:25)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.exports.__esModule (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:12241:18)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.<anonymous> (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:12719:27)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
    at Object.module.exports (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:85:19)
    at __webpack_require__ (C:\projects\myproj\node_modules\react-data-grid\dist\react-data-grid.ui-plugins.js:30:30)
```

**Expected/desired behavior**
Use either:
Specify browser usage and mock a container just for isomorphic rendering: https://github.com/defunctzombie/package-browser-field-spec
Use the `global` node.js var: https://nodejs.org/api/globals.html#globals_global (an easy implementation can be found here: https://github.com/purposeindustries/window-or-global/blob/master/lib/index.js)
Use some kind of mock-client library like JsDom: https://github.com/tmpvar/jsdom

**Comment by emorling** [comment]
@noyg did you find any solutions to this?

**Comment by noyg** [comment]
I did not, and stopped developing the feature.
Will probably be looking at submitting a PR to this lib once I get back to active development.

**Comment by emorling** [comment]
Do you have a fast and easy approach to getting the drop down editor
working? I was thinking about baking in a few of the plugins into the main
file that is working...

ons 28 dec. 2016 kl. 07:38 skrev noyg <notifications@github.com>:

**Comment by diogofcunha** [comment]
Hi @noyg.

This is a know issue, duplicated from https://github.com/adazzle/react-data-grid/issues/361.

Let's keep the conversation in there
